"""Tests for the screenshot code generated by each bridge.

The existing `get_screenshot` tests in ``test_tools_view.py`` mock the bridge, so
they never see this code. It is generated inside the bridges and executed by
FreeCAD, which is exactly where the empty-capture bug lived — hence these tests
assert on the generated source directly.
"""

from unittest.mock import AsyncMock

import pytest

from freecad_mcp.bridge.base import ExecutionResult


def _ok(result):
    return ExecutionResult(
        success=True,
        result=result,
        stdout="",
        stderr="",
        error_traceback=None,
        execution_time_ms=1.0,
    )


def _capture_screenshot_code(bridge):
    """Return the generated code that performs the capture.

    Some bridges probe for GUI availability first, so the capture is not
    necessarily the only ``execute_python`` call.
    """
    captured = []

    async def fake_execute_python(code, *_args, **_kwargs):
        captured.append(code)
        if "saveImage" not in code:
            return _ok({"gui_available": True, "GuiUp": True})
        return _ok(
            {
                "success": True,
                "data": "",
                "format": "png",
                "width": 800,
                "height": 600,
            }
        )

    bridge.execute_python = fake_execute_python
    return captured


@pytest.fixture(
    params=["xmlrpc", "socket", "embedded"],
    ids=["XmlRpcBridge", "SocketBridge", "EmbeddedBridge"],
)
def bridge(request):
    if request.param == "xmlrpc":
        from freecad_mcp.bridge.xmlrpc import XmlRpcBridge

        return XmlRpcBridge()
    if request.param == "socket":
        from freecad_mcp.bridge.socket import SocketBridge

        return SocketBridge()
    from freecad_mcp.bridge.embedded import EmbeddedBridge

    return EmbeddedBridge()


@pytest.mark.asyncio
async def test_screenshot_codegen_frames_geometry_and_restores_camera(bridge):
    """Capture must flush, fit, grab, then put the camera back — in that order."""
    captured = _capture_screenshot_code(bridge)
    bridge.is_gui_available = AsyncMock(return_value=True)

    await bridge.get_screenshot(width=800, height=600)

    code = next((c for c in captured if "saveImage" in c), None)
    assert code is not None, "no generated code performed a saveImage"

    # It is exec'd inside FreeCAD, so it must parse.
    compile(code, "<generated>", "exec")

    grab = code.index("saveImage")

    # Without these the grab can race the renderer, or frame an empty region,
    # yielding a valid PNG containing no model.
    assert code.index("updateGui") < grab
    assert code.index("fitAll") < grab
    assert code.index("getCamera") < grab

    # Without the restore, every capture re-frames the view: zoom_in, zoom_out
    # and set_camera_position become unobservable, since a screenshot is their
    # only feedback, and a read-only tool silently moves the user's view.
    assert code.index("setCamera") > grab

    # One flush before the grab, one after the restore.
    assert code.count("updateGui") >= 2


@pytest.mark.asyncio
async def test_screenshot_codegen_captures_the_requested_document(bridge):
    """A named document must be the one photographed.

    The bridge resolved ``doc_name`` and then grabbed
    ``FreeCADGui.ActiveDocument.ActiveView`` regardless, so asking for a
    document the GUI was not already showing returned a picture of whatever
    else was open. A benchmark model burned four captures diagnosing this.
    """
    captured = _capture_screenshot_code(bridge)
    bridge.is_gui_available = AsyncMock(return_value=True)

    await bridge.get_screenshot(width=800, height=600, doc_name="Target")

    code = next((c for c in captured if "saveImage" in c), None)
    assert code is not None, "no generated code performed a saveImage"
    compile(code, "<generated>", "exec")

    activate = code.find("setActiveDocument")
    assert activate != -1, "generated code never activates the requested document"

    # The document must be activated before the view is taken, otherwise the
    # view still belongs to the previously active document.
    view_lookup = code.index("ActiveView")
    assert activate < view_lookup, "document activated after the view was resolved"
    assert activate < code.index("saveImage")

    # Activating a document switches the operator's visible tab; put it back.
    assert code.count("setActiveDocument") >= 2, (
        "must restore the previously active document after capture"
    )


class TestFeatureViewCodegen:
    """The generated capture code is where correctness actually lives."""

    def test_code_checks_gui_before_touching_the_view(self):
        from freecad_mcp.bridge.view_code import build_feature_view_code

        code = build_feature_view_code(
            normal_source="WindowSketch",
            side="front",
            focus=None,
            padding=0.1,
            hide_construction=True,
            width=800,
            height=600,
            doc_name=None,
        )
        assert code.index("FreeCAD.GuiUp") < code.index("setViewDirection")

    def test_code_restores_camera_and_visibility(self):
        from freecad_mcp.bridge.view_code import build_feature_view_code

        code = build_feature_view_code(
            normal_source="WindowSketch",
            side="front",
            focus=["Pocket"],
            padding=0.1,
            hide_construction=True,
            width=800,
            height=600,
            doc_name=None,
        )
        assert "setCamera(_saved_camera)" in code
        assert "finally:" in code
        assert "_restore_visibility" in code

    def test_back_side_negates_the_normal(self):
        from freecad_mcp.bridge.view_code import build_feature_view_code

        front = build_feature_view_code(
            normal_source="S",
            side="front",
            focus=None,
            padding=0.1,
            hide_construction=False,
            width=800,
            height=600,
            doc_name=None,
        )
        back = build_feature_view_code(
            normal_source="S",
            side="back",
            focus=None,
            padding=0.1,
            hide_construction=False,
            width=800,
            height=600,
            doc_name=None,
        )
        assert front != back
        assert "_side = 'back'" in back

    def test_unresolvable_source_is_a_structured_error(self):
        from freecad_mcp.bridge.view_code import build_feature_view_code

        code = build_feature_view_code(
            normal_source="Missing",
            side="front",
            focus=None,
            padding=0.1,
            hide_construction=False,
            width=800,
            height=600,
            doc_name=None,
        )
        assert '"success": False' in code
        assert "has no resolvable support placement" in code
